apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployement
  labels:
    app: wescribe-backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wescribe-backend
  template: 
    metadata:
      labels:
        app: wescribe-backend
    spec:
      containers:
        - name: backend-container
          image: dhanush29/wescribe-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: wescribe-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001