apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: wescribe-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001