---
- name: Deploying backend with Kubernetes
  hosts: localhost
  remote_user: dhanush

  collections:
    - community.kubernetes

  tasks:
    - name: create backend deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './k8s-deploy-backend.yaml') | from_yaml }}"
        state: present
    - name: create backend service
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './k8s-service-backend.yaml') | from_yaml }}" 
        state: present