apiVersion: apps/v1
kind: Deployment
metadata:
  name: wescribe-backend
  labels:
    app: wescribe-backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: wescribe-backend
  template: 
    metadata:
      labels:
        app: wescribe-backend
    spec:
      containers:
        - name: backend-container
          image: dhanush29/wescribe-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000