apiVersion: v1
kind: PersistentVolume
metadata:
  name: wescribe-pv-volume
  labels:
    type: local
spec:
  storageClassName: wescribe-pv-volume
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"