apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  loadBalancerIP: "0.0.0.0"
  selector:
    app: wescribe-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000