# Generated by Django 3.1.6 on 2021-02-17 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210215_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, default='Notes', max_length=200),
        ),
    ]
