# Generated by Django 3.1.6 on 2021-02-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210217_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='title',
        ),
    ]
