# Generated by Django 3.1.6 on 2021-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210217_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='boardID',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
