# Generated by Django 3.1.6 on 2021-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210219_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='videoLink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
